#!/bin/bash -l

#.Declare a name for this job to be my_serial_job
#.it is recommended that this name be kept to 16 characters or less
#SBATCH -J w1xOA

#SBATCH --qos pppl-short

#.Number of nodes to request (Cori has 32/64 physics/logical cores per node)
#SBATCH -N 1

#.Total number of cores (96 per node).
#SBATCH --tasks-per-node=4

#.Request wall time
#SBATCH -t 24:00:00

#.Request a GPU.
#SBATCH --gres=gpu:2
num_gpu=2             #[ Number of GPUs to use (1 or 2).

#.Specify name format of output file.
#SBATCH -o slurm-%j.out

# If doing a restart indicate restart file path. Must also
# add it as a command line argument after outdir below.

module load cudatoolkit/12.4
module load openmpi/cuda-11.1/gcc/4.1.1

#[ Alternate between a regular dynamics phase (RDP)
#[ and an orbit averaging phase (OAP).
oap_first=0          #[ Whether to run OAP first (1) or RDP first (0).
# alpha_oap=0.000005         #[ Factor mulplying collisionless terms in OAP.
alpha_rdp=1.0          #[ Factor mulplying collisionless terms in RDP.
# tau_oap=500000          #[ Simulation time for OAP (in microsec).
tau_rdp=1000            #[ Simulation time for RDP (in microsec).
# tau_rdp_extra=0.0     #[ Simulation time for final RDP (in microsec).
# static_field_oap=0     #[ Whether to use a static field in OAP.
static_field_rdp=0     #[ Whether to use a static field in RDP.
# mask_loss_fac_oap=0.0  #[ Value of the mask in the loss region in OAP.
mask_loss_fac_rdp=1.0  #[ Value of the mask in the loss region in RDP.
# fdot_mult_type_oap=2   #[ Type of mask applied to df/dt in OAP.
fdot_mult_type_rdp=0   #[ Type of mask applied to df/dt in RDP.
# num_cycles=100          #[ Number of RDP-OAP pairs to run.
frames_per_phase=100    #[ Number of output frames for each of RDP/OAP.

srun -u -n $num_gpu ./sim -g -M -c $num_gpu -o alpha=$alpha_rdp,t_end=$tau_rdp,num_frames=$frames_per_phase,static_field=$static_field_rdp,I_loss=$mask_loss_fac_rdp,fdot_mult_type=$fdot_mult_type_rdp