#!/bin/bash -l

#.Declare a name for this job to be my_serial_job
#.it is recommended that this name be kept to 16 characters or less
#SBATCH -J w1xOA

#SBATCH --qos pppl-short

#.Number of nodes to request (Cori has 32/64 physics/logical cores per node)
#SBATCH -N 1

#.Total number of cores (96 per node).
#SBATCH --tasks-per-node=4

#.Request wall time
#SBATCH -t 24:00:00

#.Request a GPU.
#SBATCH --gres=gpu:2
num_gpu=2             #[ Number of GPUs to use (1 or 2).

#.Specify name format of output file.
#SBATCH -o slurm-%j.out

# If doing a restart indicate restart file path. Must also
# add it as a command line argument after outdir below.

module load cudatoolkit/12.4
module load openmpi/cuda-11.1/gcc/4.1.1

#[ Alternate between a regular dynamics phase (RDP)
#[ and an orbit averaging phase (OAP).
oap_first=0          #[ Whether to run OAP first (1) or RDP first (0).
alpha_oap=0.000005         #[ Factor mulplying collisionless terms in OAP.
alpha_rdp=1.0          #[ Factor mulplying collisionless terms in RDP.
tau_oap=500000          #[ Simulation time for OAP (in microsec).
tau_rdp=10            #[ Simulation time for RDP (in microsec).
tau_rdp_extra=100.0     #[ Simulation time for final RDP (in microsec).
static_field_oap=0     #[ Whether to use a static field in OAP.
static_field_rdp=0     #[ Whether to use a static field in RDP.
mask_loss_fac_oap=0.0  #[ Value of the mask in the loss region in OAP.
mask_loss_fac_rdp=1.0  #[ Value of the mask in the loss region in RDP.
fdot_mult_type_oap=2   #[ Type of mask applied to df/dt in OAP.
fdot_mult_type_rdp=0   #[ Type of mask applied to df/dt in RDP.
positivity_oap=0       #[ Whether to use positivity hack in OAP.
positivity_rdp=1       #[ Whether to use positivity hack in RDP.
num_cycles=2          #[ Number of RDP-OAP pairs to run.
frames_per_phase=5    #[ Number of output frames for each of RDP/OAP.

frames_per_cycle=$(echo "$frames_per_phase * 2" | bc)

# Function to run Orbit Averaging Phase (OAP)
run_OAP() {
    local tfinal=$1
    local frame_start_phase=$2
    local frame_end_phase=$3

    echo "OAP: tfinal=$tfinal | frame_start_phase=$frame_start_phase | frame_end_phase=$frame_end_phase"

    option_string="alpha=$alpha_oap,t_end=$tfinal,num_frames=$frame_end_phase,static_field=$static_field_oap,I_loss=$mask_loss_fac_oap,fdot_mult_type=$fdot_mult_type_oap,use_positivity_hack=$positivity_oap"
    # If previous frames are zero, drop the restart argument
    if [ "$frame_start_phase" -eq 0 ]; then
        if [ "$num_gpu" -eq 2 ]; then
            echo "srun -n 2 ./sim -g -M -c 2 -o $option_string"
            srun -u -n 2 ./sim -g -M -c 2 -o $option_string
        else
            echo "./sim -g -o $option_string"
            ./sim -g -o $option_string
        fi
    else
        if [ "$num_gpu" -eq 2 ]; then
            echo "srun -n 2 ./sim -g -M -c 2 -r $frame_start_phase -o $option_string"
            srun -u -n 2 ./sim -g -M -c 2 -r $frame_start_phase -o $option_string
        else
            echo "./sim -g -r $frame_start_phase -o $option_string"
            ./sim -g -r $frame_start_phase -o $option_string
        fi
    fi
}

# Function to run Regular Dynamics Phase (RDP)
run_RDP() {
    local tfinal=$1
    local frame_start_phase=$2
    local frame_end_phase=$3

    echo "RDP: tfinal=$tfinal | frame_start_phase=$frame_start_phase | frame_end_phase=$frame_end_phase"

    option_string="alpha=$alpha_rdp,t_end=$tfinal,num_frames=$frame_end_phase,static_field=$static_field_rdp,I_loss=$mask_loss_fac_rdp,fdot_mult_type=$fdot_mult_type_rdp,use_positivity_hack=$positivity_rdp"
    # If previous frames are zero, drop the restart argument
    if [ "$frame_start_phase" -eq 0 ]; then
        if [ "$num_gpu" -eq 2 ]; then
            echo "srun -n 2 ./sim -g -M -c 2 -o $option_string"
            srun -u -n 2 ./sim -g -M -c 2 -o $option_string
        else
            echo "./sim -g -o $option_string"
            ./sim -g -o $option_string
        fi
    else
        if [ "$num_gpu" -eq 2 ]; then
            echo "srun -n 2 ./sim -g -M -c 2 -r $frame_start_phase -o $option_string"
            srun -u -n 2 ./sim -g -M -c 2 -r $frame_start_phase -o $option_string
        else
            echo "./sim -g -r $frame_start_phase -o $option_string"
            ./sim -g -r $frame_start_phase -o $option_string
        fi
    fi
}

tfinal=0.0  # Initialize final time
frame_end_phase=0  # Initialize previous frames
if [ "$oap_first" -eq 1 ]; then
    echo "Running OAP first"
    # Main loop for alternating OAP-RDP cycles
    for ((i=0; i<$num_cycles; i++)); do
        # OAP phase
        tfinal=$(echo "$tfinal + $tau_oap" | bc)
        frame_start_phase=$frame_end_phase
        frame_end_phase=$((frame_end_phase + frames_per_phase))
        run_OAP $tfinal $frame_start_phase $frame_end_phase

        # RDP phase
        tfinal=$(echo "$tfinal + $tau_rdp" | bc)
        frame_start_phase=$frame_end_phase
        frame_end_phase=$((frame_end_phase + frames_per_phase))
        run_RDP $tfinal $frame_start_phase $frame_end_phase
    done

    # # Final RDP phase with a few extra frames
    echo "Final RDP phase with extra frames"
    tfinal=$(echo "$tfinal + $tau_rdp_extra" | bc)
    frame_start_phase=$frame_end_phase
    frame_end_phase=$(echo "$frame_end_phase + ($tau_rdp_extra / $tau_rdp) * $frames_per_phase" | bc)
    run_RDP $tfinal $frame_start_phase $frame_end_phase

else
    echo "Running RDP first"
    # Main loop for alternating RDP-OAP cycles
    for ((i=0; i<$num_cycles; i++)); do
        # RDP phase
        tfinal=$(echo "$tfinal+$tau_rdp" | bc)
        frame_start_phase=$frame_end_phase
        frame_end_phase=$((frame_end_phase + frames_per_phase))
        run_RDP $tfinal $frame_start_phase $frame_end_phase

        # OAP phase
        tfinal=$(echo "$tfinal + $tau_oap" | bc)
        frame_start_phase=$frame_end_phase
        frame_end_phase=$((frame_end_phase + frames_per_phase))
        run_OAP $tfinal $frame_start_phase $frame_end_phase
    done

    # # Final RDP phase with a few extra frames
    echo "Final RDP phase with extra frames"
    tfinal=$(echo "$tfinal + $tau_rdp_extra" | bc)
    frame_start_phase=$frame_end_phase
    frame_end_phase=$(echo "$frame_end_phase + ($tau_rdp_extra / $tau_rdp) * $frames_per_phase" | bc)
    run_RDP $tfinal $frame_start_phase $frame_end_phase
fi

exit 0
