#!/bin/bash -l

#.Declare a name for this job, preferably with 16 or fewer characters.
#SBATCH -J 1x-beams-higher-alpha
#SBATCH -A m4487

#.Request the queue (enter the possible names, if omitted, default is the default)
#.this job is going to use the default
#SBATCH -q regular
#SBATCH -C gpu 

#.Number of nodes to request (Perlmutter has 64 cores and 4 GPUs per node)
#SBATCH -N 2
#SBATCH --ntasks 8

#.Specify GPU needs:
#SBATCH --constraint gpu
#SBATCH --gpus 8

#.Request wall time
#SBATCH -t 24:00:00

#.Mail is sent to you when the job starts and when it terminates or aborts.
#SBATCH --mail-user=mhrosen@pppl.gov
#SBATCH --mail-type=ALL
num_gpu=8

module load PrgEnv-gnu/8.6.0
module load craype-accel-nvidia80
module load cray-mpich/9.0.1
module load cudatoolkit/13.0
module load nccl/2.29.2-cu13
module load cray-libsci/25.09.0  #.Disable CUDA-ware MPI, since it causes problems on Perlmutter and we use NCCL alone.
export MPICH_GPU_SUPPORT_ENABLED=0

#.On Perlmutter some jobs get warnings about DVS_MAXNODES (used in file stripping).
#.We set it to 24 for now, but really this depends on the amount/size of I/O being performed.
#.See online NERSC docs and the intro_mpi man page.
export DVS_MAXNODES=24_
export MPICH_MPIIO_DVS_MAXNODES=24

# Safely route GPUDirect RDMA over the Host Bridge
export NCCL_NET_GDR_LEVEL=PHB

# Tell NCCL to use the Libfabric plugin
export NCCL_NET="AWS Libfabric"
export NCCL_CROSS_NIC=1

# Disable host registration and eager messages to prevent Slingshot 11 hangs
export FI_CXI_DISABLE_HOST_REGISTER=1
export FI_CXI_RDZV_GET_MIN=0
export FI_CXI_RDZV_THRESHOLD=0
export FI_CXI_RDZV_EAGER_SIZE=0

max_number=-1
file_prefix="zzim-ion_"
shopt -s nullglob
matching_files=("${file_prefix}"[0-9]*.gkyl)
for file in "${matching_files[@]}"; do
  number=${file#"$file_prefix"}
  number=${number%.gkyl}
  if [[ $number =~ ^[0-9]+$ ]] && (( 10#$number > max_number )); then
    max_number=$((10#$number))
  fi
done
echo "Max number is $max_number"

if [ "$max_number" -lt 0 ]; then
  echo "No matching files found. Starting from the beginning"
  if [ "$num_gpu" -eq 1 ]; then
    echo "./sim -g"
    ./sim -g
    sim_status=$?
  else
    echo "srun -u -n $num_gpu ./sim -g -M -c $num_gpu"
    srun -u -n $num_gpu --gpus $num_gpu ./sim -g -M -c $num_gpu
    sim_status=$?
  fi
else
  echo "Resuming from file $max_number"
  if [ "$num_gpu" -eq 1 ]; then
    echo "./sim -g -r $max_number"
    ./sim -g -r $max_number
    sim_status=$?
  else
    echo "srun -u -n $num_gpu ./sim -g -M -c $num_gpu -r $max_number"
    srun -u -n $num_gpu --gpus $num_gpu ./sim -g -M -c $num_gpu -r $max_number
    sim_status=$?
  fi
fi

exit "$sim_status"
