mkdir -p python-plots

pgkyl "gk_wham-field_[0-9]*.gkyl" interp sel --z0 0.0 col pl --title 'Midplane electrostatic potential' --xlabel 'Time (s)' --ylabel 'Electric Potential φ (V)' --saveas python-plots/field_potential_z0_vs_time.png --no-show &

pgkyl gk_wham-ion_bflux_xupper_integrated_M0M1M2parM2perp.gkyl sel -c0 pl --title 'Upper Boundary Flux' --xlabel 'Time (s)' --logy --scatter --saveas python-plots/ion_bflux_xupper_M0_vs_time.png --no-show &

pgkyl gk_wham-ion_integrated_moms.gkyl pl --title 'Integrated Ion Moments' --xlabel 'Time (s)' --scatter --saveas python-plots/ion_integrated_moments_vs_time.png --no-show &

pgkyl "gk_wham-ion_BiMaxwellianMoments_[0-9]*.gkyl" interp col pl --title 'Ion BiMaxwellian Moments' --xlabel 'Time (s)' --ylabel 'BiMaxwellian Moments' --saveas python-plots/ion_BiMaxwellian_moments_vs_time.png --no-show &

frame=$(ls gk_wham-ion_BiMaxwellianMoments_*.gkyl | sed -E 's/.*_([0-9]+)\.gkyl/\1/' | sort -n | tail -1)
pgkyl --c2p-vel gk_wham-ion_mapc2p_vel.gkyl gk_wham-ion_${frame}.gkyl interp sel --z0 0.0 ev 'f abs' pl --xlabel 'Parallel Velocity $v_\parallel$ (m/s)' --ylabel 'Magnetic Moment $\mu$ (J/T)' --logz --zmin 1e-25 --title "Ion Distribution Function at z=0.0 (Frame ${frame}) - WHAM1X" --saveas python-plots/ion_distf_z0.0_frame${frame}.png --no-show &
pgkyl --c2p-vel gk_wham-ion_mapc2p_vel.gkyl gk_wham-ion_${frame}.gkyl interp sel --z0 0.5 ev 'f abs' pl --xlabel 'Parallel Velocity $v_\parallel$ (m/s)' --ylabel 'Magnetic Moment $\mu$ (J/T)' --logz --zmin 1e-25 --title "Ion Distribution Function at z=0.5 (Frame ${frame}) - WHAM1X" --saveas python-plots/ion_distf_z0.5_frame${frame}.png --no-show &
pgkyl --c2p-vel gk_wham-ion_mapc2p_vel.gkyl gk_wham-ion_${frame}.gkyl interp sel --z0 1.0 ev 'f abs' pl --xlabel 'Parallel Velocity $v_\parallel$ (m/s)' --ylabel 'Magnetic Moment $\mu$ (J/T)' --logz --zmin 1e-25 --title "Ion Distribution Function at z=1.0 (Frame ${frame}) - WHAM1X" --saveas python-plots/ion_distf_z1.0_frame${frame}.png --no-show &
pgkyl --c2p-vel gk_wham-ion_mapc2p_vel.gkyl gk_wham-ion_${frame}.gkyl interp sel --z0 1.5 ev 'f abs' pl --xlabel 'Parallel Velocity $v_\parallel$ (m/s)' --ylabel 'Magnetic Moment $\mu$ (J/T)' --logz --zmin 1e-25 --title "Ion Distribution Function at z=1.5 (Frame ${frame}) - WHAM1X" --saveas python-plots/ion_distf_z1.5_frame${frame}.png --no-show &
pgkyl --c2p-vel gk_wham-ion_mapc2p_vel.gkyl gk_wham-ion_${frame}.gkyl interp sel --z0 1.9 ev 'f abs' pl --xlabel 'Parallel Velocity $v_\parallel$ (m/s)' --ylabel 'Magnetic Moment $\mu$ (J/T)' --logz --zmin 1e-25 --title "Ion Distribution Function at z=1.9 (Frame ${frame}) - WHAM1X" --saveas python-plots/ion_distf_z1.9_frame${frame}.png --no-show &
pgkyl --c2p-vel gk_wham-ion_mapc2p_vel.gkyl gk_wham-ion_${frame}.gkyl interp integ 2 ev 'f abs' pl --xlabel 'Axial Position z (m)' --ylabel 'Parallel Velocity $v_\parallel$ (m/s)' --logz --zmin 1e-35 --title "Ion Distribution Integrated over μ (Frame ${frame}) - WHAM1X" --saveas python-plots/ion_distf_integrated_mu_frame${frame}.png --no-show &
pgkyl --c2p-vel gk_wham-ion_mapc2p_vel.gkyl gk_wham-ion_${frame}.gkyl interp integ 1 ev 'f abs' pl --xlabel 'Axial Position z (m)' --ylabel 'Magnetic Moment $\mu$ (J/T)' --logz --zmin 1e-10 --title "Ion Distribution Integrated over $v_\parallel$ (Frame ${frame}) - WHAM1X" --saveas python-plots/ion_distf_integrated_vpar_frame${frame}.png --no-show &
pgkyl gk_wham-ion_BiMaxwellianMoments_${frame}.gkyl interp pl --xlabel 'Axial Position z (m)' --title 'Ion BiMaxwellian Moments at z=0.0' --saveas python-plots/ion_BiMaxwellian_moments_z0.0_frame${frame}.png --no-show &

pgkyl gk_wham-field_${frame}.gkyl interp pl --title 'Midplane electrostatic potential' --xlabel 'Time (s)' --ylabel 'Electric Potential φ (V)' --saveas python-plots/field_potential_z0_vs_time_frame${frame}.png --no-show &

pgkyl --c2p-vel gk_wham-ion_mapc2p_vel.gkyl gk_wham-ion_source_0.gkyl gk_wham-ion_0.gkyl interp sel --z2 0.5 pl -c --xlabel 'Axial Position z (m)' --ylabel 'Parallel Velocity $v_\parallel$ (m/s)' --title 'Ion Source vs Distribution at $z_2=0.5$ (Frame 0) - WHAM1X' --logz --zmin 1e-25 --saveas python-plots/ion_source_vs_distf_z0.5_frame0.png --no-show &
pgkyl --c2p-vel gk_wham-ion_mapc2p_vel.gkyl gk_wham-ion_source_0.gkyl interp sel --z2 0.5 pl -c --xlabel 'Axial Position z (m)' --ylabel 'Parallel Velocity $v_\parallel$ (m/s)' --title 'Ion Source at $z_2=0.5$ (Frame 0) - WHAM1X' --logz --zmin 1e-25 --saveas python-plots/ion_source_z0.5_frame0.png --no-show &
pgkyl --c2p-vel gk_wham-ion_mapc2p_vel.gkyl gk_wham-ion_0.gkyl interp sel --z2 0.5 pl -c --xlabel 'Axial Position z (m)' --ylabel 'Parallel Velocity $v_\parallel$ (m/s)' --title 'Ion Distribution at $z_2=0.5$ (Frame 0) - WHAM1X' --logz --zmin 1e-25 --saveas python-plots/ion_distf_z0.5_frame0.png --no-show &

pgkyl gk_wham-ion_source_HamiltonianMoments_0.gkyl interp pl --xlabel 'Axial Position z (m)' --title 'Source Hamiltonian Moments' --logz --zmin 1e-25 --saveas python-plots/ion_source_HamiltonianMoments_frame0.png --no-show &

# Electron plots similar to ion plots
pgkyl gk_wham-elc_bflux_xupper_integrated_M0M1M2parM2perp.gkyl sel -c0 pl --title 'Upper Boundary Flux (Electrons)' --xlabel 'Time (s)' --logy --scatter --saveas python-plots/elc_bflux_xupper_M0_vs_time.png --no-show &

pgkyl gk_wham-elc_integrated_moms.gkyl pl --title 'Integrated Electron Moments' --xlabel 'Time (s)' --scatter --saveas python-plots/elc_integrated_moments_vs_time.png --no-show &

pgkyl "gk_wham-elc_BiMaxwellianMoments_[0-9]*.gkyl" interp col pl --title 'Electron BiMaxwellian Moments' --xlabel 'Time (s)' --ylabel 'BiMaxwellian Moments' --saveas python-plots/elc_BiMaxwellian_moments_vs_time.png --no-show &

elc_frame=$(ls gk_wham-elc_BiMaxwellianMoments_*.gkyl | sed -E 's/.*_([0-9]+)\.gkyl/\1/' | sort -n | tail -1)
pgkyl --c2p-vel gk_wham-elc_mapc2p_vel.gkyl gk_wham-elc_${elc_frame}.gkyl interp sel --z0 0.0 ev 'f abs' pl --xlabel 'Parallel Velocity $v_\parallel$ (m/s)' --ylabel 'Magnetic Moment $\mu$ (J/T)' --logz --zmin 1e-25 --title "Electron Distribution Function at z=0.0 (Frame ${elc_frame}) - WHAM1X" --saveas python-plots/elc_distf_z0.0_frame${elc_frame}.png --no-show &
pgkyl --c2p-vel gk_wham-elc_mapc2p_vel.gkyl gk_wham-elc_${elc_frame}.gkyl interp sel --z0 0.5 ev 'f abs' pl --xlabel 'Parallel Velocity $v_\parallel$ (m/s)' --ylabel 'Magnetic Moment $\mu$ (J/T)' --logz --zmin 1e-25 --title "Electron Distribution Function at z=0.5 (Frame ${elc_frame}) - WHAM1X" --saveas python-plots/elc_distf_z0.5_frame${elc_frame}.png --no-show &
pgkyl --c2p-vel gk_wham-elc_mapc2p_vel.gkyl gk_wham-elc_${elc_frame}.gkyl interp sel --z0 1.0 ev 'f abs' pl --xlabel 'Parallel Velocity $v_\parallel$ (m/s)' --ylabel 'Magnetic Moment $\mu$ (J/T)' --logz --zmin 1e-25 --title "Electron Distribution Function at z=1.0 (Frame ${elc_frame}) - WHAM1X" --saveas python-plots/elc_distf_z1.0_frame${elc_frame}.png --no-show &
pgkyl --c2p-vel gk_wham-elc_mapc2p_vel.gkyl gk_wham-elc_${elc_frame}.gkyl interp sel --z0 1.5 ev 'f abs' pl --xlabel 'Parallel Velocity $v_\parallel$ (m/s)' --ylabel 'Magnetic Moment $\mu$ (J/T)' --logz --zmin 1e-25 --title "Electron Distribution Function at z=1.5 (Frame ${elc_frame}) - WHAM1X" --saveas python-plots/elc_distf_z1.5_frame${elc_frame}.png --no-show &
pgkyl --c2p-vel gk_wham-elc_mapc2p_vel.gkyl gk_wham-elc_${elc_frame}.gkyl interp sel --z0 1.9 ev 'f abs' pl --xlabel 'Parallel Velocity $v_\parallel$ (m/s)' --ylabel 'Magnetic Moment $\mu$ (J/T)' --logz --zmin 1e-25 --title "Electron Distribution Function at z=1.9 (Frame ${elc_frame}) - WHAM1X" --saveas python-plots/elc_distf_z1.9_frame${elc_frame}.png --no-show &
pgkyl --c2p-vel gk_wham-elc_mapc2p_vel.gkyl gk_wham-elc_${elc_frame}.gkyl interp integ 2 ev 'f abs' pl --xlabel 'Axial Position z (m)' --ylabel 'Parallel Velocity $v_\parallel$ (m/s)' --logz --zmin 1e-35 --title "Electron Distribution Integrated over μ (Frame ${elc_frame}) - WHAM1X" --saveas python-plots/elc_distf_integrated_mu_frame${elc_frame}.png --no-show &
pgkyl --c2p-vel gk_wham-elc_mapc2p_vel.gkyl gk_wham-elc_${elc_frame}.gkyl interp integ 1 ev 'f abs' pl --xlabel 'Axial Position z (m)' --ylabel 'Magnetic Moment $\mu$ (J/T)' --logz --zmin 1e-10 --title "Electron Distribution Integrated over $v_\parallel$ (Frame ${elc_frame}) - WHAM1X" --saveas python-plots/elc_distf_integrated_vpar_frame${elc_frame}.png --no-show &
pgkyl gk_wham-elc_BiMaxwellianMoments_${elc_frame}.gkyl interp pl --xlabel 'Axial Position z (m)' --title 'Electron BiMaxwellian Moments at z=0.0' --saveas python-plots/elc_BiMaxwellian_moments_z0.0_frame${elc_frame}.png --no-show &

pgkyl --c2p-vel gk_wham-elc_mapc2p_vel.gkyl gk_wham-elc_source_0.gkyl gk_wham-elc_0.gkyl interp sel --z2 0.5 pl -c --xlabel 'Axial Position z (m)' --ylabel 'Parallel Velocity $v_\parallel$ (m/s)' --title 'Electron Source vs Distribution at $z_2=0.5$ (Frame 0) - WHAM1X' --logz --zmin 1e-25 --saveas python-plots/elc_source_vs_distf_z0.5_frame0.png --no-show &
pgkyl --c2p-vel gk_wham-elc_mapc2p_vel.gkyl gk_wham-elc_source_0.gkyl interp sel --z2 0.5 pl -c --xlabel 'Axial Position z (m)' --ylabel 'Parallel Velocity $v_\parallel$ (m/s)' --title 'Electron Source at $z_2=0.5$ (Frame 0) - WHAM1X' --logz --zmin 1e-25 --saveas python-plots/elc_source_z0.5_frame0.png --no-show &
pgkyl --c2p-vel gk_wham-elc_mapc2p_vel.gkyl gk_wham-elc_0.gkyl interp sel --z2 0.5 pl -c --xlabel 'Axial Position z (m)' --ylabel 'Parallel Velocity $v_\parallel$ (m/s)' --title 'Electron Distribution at $z_2=0.5$ (Frame 0) - WHAM1X' --logz --zmin 1e-25 --saveas python-plots/elc_distf_z0.5_frame0.png --no-show &

pgkyl gk_wham-elc_source_HamiltonianMoments_0.gkyl interp pl --xlabel 'Axial Position z (m)' --title 'Electron Source Hamiltonian Moments' --logz --zmin 1e-25 --saveas python-plots/elc_source_HamiltonianMoments_frame0.png --no-show &