#!/bin/bash -l

#.Declare a name for this job, preferably with 16 or fewer characters.
#SBATCH -J l2x-R5-POA
#SBATCH -A m4487

#.Request the queue (enter the possible names, if omitted, default is the default)
#.this job is going to use the default
#SBATCH -q regular
#SBATCH -C gpu 

#.Number of nodes to request (Perlmutter has 64 cores and 4 GPUs per node)
#SBATCH -N 2
#SBATCH --ntasks 8

#.Specify GPU needs:
#SBATCH --constraint gpu
# SBATCH --gpus 8

#.Request wall time
#SBATCH -t 24:00:00

#.Mail is sent to you when the job starts and when it terminates or aborts.
#SBATCH --mail-user=mhrosen@pppl.gov
#SBATCH --mail-type=ALL
num_gpu=8

#.Load modules (this must match those in the machines/configure script).
module load PrgEnv-gnu/8.6.0
module load craype-accel-nvidia80
module load cray-mpich/9.0.1
module load cudatoolkit/13.0
module load nccl/2.29.2-cu13
module load cray-libsci/25.09.0

#.Disable CUDA-ware MPI, since it causes problems on Perlmutter and we use NCCL alone.
export MPICH_GPU_SUPPORT_ENABLED=0

#.On Perlmutter some jobs get warnings about DVS_MAXNODES (used in file stripping).
#.We set it to 24 for now, but really this depends on the amount/size of I/O being performed.
#.See online NERSC docs and the intro_mpi man page.
export DVS_MAXNODES=24_
export MPICH_MPIIO_DVS_MAXNODES=24

max_number=0
file_prefix="gk_lorentzian_mirror-ion_"
file_extension="[0-9]*.gkyl"
matching_files=$(ls $file_prefix$file_extension)
for file in $matching_files; do
  # # Extract the number between the prefix and suffix
  number=$(echo "$file" | sed "s|$file_prefix||; s|\.gkyl||")
  # If the number is greater than the current max_number, update max_number and max_file
  if [ "$number" -gt "$max_number" ]; then
    max_number="$number"
  fi
done
echo "Max number is $max_number"

if [ "$max_number" -eq 0 ]; then
  echo "No matching files found. Starting from the begining"
  if [ "$num_gpu" -eq 1 ]; then
    echo "./sim -g"
    ./sim -g
  else
    echo "srun -u -n $num_gpu ./sim -g -M -d $num_gpu"
    srun -u -n $num_gpu --gpus $num_gpu ./sim -g -M -d $num_gpu
  fi
else
  echo "Resuming from file $max_number"
  if [ "$num_gpu" -eq 1 ]; then
    echo "./sim -g -r $max_number"
    ./sim -g -r $max_number
  else
    echo "srun -u -n $num_gpu ./sim -g -M -d $num_gpu -r $max_number"
    srun -u -n $num_gpu --gpus $num_gpu ./sim -g -M -d $num_gpu -r $max_number
  fi
fi
